### ISSUE TITLE
Why am I getting "Error: functions are not supported" on a call to Meteor Collection.update()

### ISSUE THREAD

**Issue by mixersoft** [Urigo/angular-meteor#1276]
I am getting `Exception in queued task: Error: functions are not supported` when I try to update a document. To isolate, I issued the update command multiple times in the console. To my surprise, the record is actually updated the first time-and I get an error. When I repeat the call, the method has not effect and there is no exception.

Thoughts?

using `angular-meteor#1.3.7` , `meteor-client-side#0.2.3` with `ionic#1.2.4` (`angular#1.4.3`)
```
mcFeeds.update({_id:"ogtA9NejENwAteewo"}, {$addToSet:{'head.likes':"xBYWvthK5qZ5zHx9T"}})
meteor-client-side.bundle.js:2275 Exception in queued task: Error: functions are not supported
    at trivialMatchesDiffFilter (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9003:11)
    at Pipe.process (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9157:5)
    at Processor.process (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9299:12)
    at DiffPatcher.diff (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:8149:25)
    at Object.exports.diff (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9099:30)
    at Object.changedAt (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:11523:35)
    at observeChangesCallbacks.changed (http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:10160:28)
    at Object.self.applyChange.changed (http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:10113:44)
    at http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:6696:13
    at _.extend.runTask (http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:2080:11)
1
mcFeeds.update({_id:"ogtA9NejENwAteewo"}, {$addToSet:{'head.likes':"xBYWvthK5qZ5zHx9T"}})
1
mcFeeds.update({_id:"ogtA9NejENwAteewo"}, {$pull:{'head.likes':"xBYWvthK5qZ5zHx9T"}})
meteor-client-side.bundle.js:2275 Exception in queued task: Error: functions are not supported
    at trivialMatchesDiffFilter (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9003:11)
    at Pipe.process (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9157:5)
    at Processor.process (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9299:12)
    at DiffPatcher.diff (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:8149:25)
    at Object.exports.diff (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:9099:30)
    at Object.changedAt (http://localhost:3000/lib/angular-meteor/dist/angular-meteor.bundle.js:11523:35)
    at observeChangesCallbacks.changed (http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:10160:28)
    at Object.self.applyChange.changed (http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:10113:44)
    at http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:6696:13
    at _.extend.runTask (http://localhost:3000/lib/meteor-client-side/dist/meteor-client-side.bundle.js:2080:11)
1
mcFeeds.update({_id:"ogtA9NejENwAteewo"}, {$pull:{'head.likes':"xBYWvthK5qZ5zHx9T"}})
1
```

**Comment by mixersoft** [comment]
found it. It's because `angular-meteor` is not compatible with this pattern:

```
// Comments collection
Comments = new Mongo.Collection("comments", {
  transform: function(doc) {
    return new Comment(doc);
  }
});
```

see: https://dweldon.silvrback.com/models

**Comment by kmcmanimen** [comment]
mixersoft - how did you solve for this?  I am getting the same error and tried to approach outlined in the link to no avail.

My current code:
export const Projects = new Mongo.Collection('projects', {
  transform: function (doc) {
      doc.remaining = function () {
        var minute = 1000*60;
        var hour = minute*60;
        var day = hour*24;
        var length = day * 7;

        if(!this.expires)
            return null;

        time_remaining = this.expires - new Date();
        if(time_remaining < 0)
          return {label: 'Complete'};

        if(time_remaining > day)
          return {value: Math.round(time_remaining / day), label : "Days Remaining"};
        else if(time_remaining > hour)
          return {value: Math.round(time_remaining / hour), label : "Hours Remaining"};
        else if(time_remaining > minute)
          return {value: Math.round(time_remaining / minute), label : "Minutes Remaining"};
        else
          return {value: '<1', label : "Minute Remaining"};
      };
    return doc;
  }
});

Everything works on the initial call but when I change the sort order and reactively call a second time to the server, I get the error below.  I can change the selection criteria without error but not the sort order.

Exception from Tracker recompute function:
meteor.js?hash=e3f53db…:930 Error: functions are not supported
    at trivialMatchesDiffFilter (modules.js?hash=c8bf21b…:37145)
    at Pipe.process (modules.js?hash=c8bf21b…:36850)
    at Processor.process (modules.js?hash=c8bf21b…:36807)
    at DiffPatcher.diff (modules.js?hash=c8bf21b…:36735)
    at Object.exports.diff (modules.js?hash=c8bf21b…:36627)
    at modules.js?hash=c8bf21b…:34865
    at Object.Tracker.nonreactive (tracker.js?hash=9f8a0ce…:631)
    at Scope.<anonymous> (modules.js?hash=c8bf21b…:34844)
    at modules.js?hash=c8bf21b…:34185
    at Tracker.Computation._compute (tracker.js?hash=9f8a0ce…:339)

**Comment by dongzhi-yang** [comment]
Hi ,
Is there a fix to this issue? 
Any plan to enable angular-meteor to support 'transform'?

Thanks
