### ISSUE TITLE
How to run angular with meteor 1.3?

### ISSUE THREAD

**Issue by Deadly0** [Urigo/angular-meteor#1300]
I was asked this question at [StackOverflow](http://stackoverflow.com/questions/35729076/meteor-1-3-and-angular-1) some weeks ago but still no correct answer.

I've copy code from angular-meteor tutorial, update meteor to 1.3 and install angular-meteor from npm, import angular and angular-meteor to the js file. Then i run meteor and got error:
```
(function(Npm,Assets){(function(){import angular from 'angular';
W20160328-21:13:36.915(3)? (STDERR)                                   ^^^^^^
W20160328-21:13:36.915(3)? (STDERR) SyntaxError: Unexpected reserved word
```

Is angular-meteor working with meteor@1.3 now? If yes, can someone explain how to do it?

**Comment by kamilkisiela** [comment]
Try to use `1.3.9` release. It should be fully compatible with Meteor@1.3 :)

**Comment by Deadly0** [comment]
@kamilkisiela i used 1.3.9 in the message above and got the error. I've also tried install it from Atmosphere but got another error:
```
Unable to resolve some modules:

  "underscore" in /C/Users/Deadly/AppData/Local/.meteor/packages/angular-meteor-data/1.3.9/web.browser/.npm/package/node_modules/angular-meteor/dist/angular-meteor.js (web.browser)
  "jsondiffpatch" in /C/Users/Deadly/AppData/Local/.meteor/packages/angular-meteor-data/1.3.9/web.browser/.npm/package/node_modules/angular-meteor/dist/angular-meteor.js (web.browser)

Consider running: meteor npm install --save underscore jsondiffpatch
```

**Comment by Deadly0** [comment]
Maybe some problems with ecmascript/angular-babel?
```
allow-deny@1.0.2
angular@1.3.9
angular-meteor-data@1.3.9
angular-templates@1.0.2
angular:angular@1.4.8
autopublish@1.0.5
autoupdate@1.2.6
babel-compiler@6.5.2
babel-runtime@0.1.6
base64@1.0.6
benjamine:jsondiffpatch@0.1.38_1
binary-heap@1.0.6
blaze@2.1.5
blaze-tools@1.0.6
boilerplate-generator@1.0.6
caching-compiler@1.0.2
caching-html-compiler@1.0.4
callback-hook@1.0.6
check@1.1.2
dburles:mongo-collection-instances@0.3.4
ddp@1.2.3
ddp-client@1.2.3
ddp-common@1.2.3
ddp-server@1.2.4
deps@1.0.10
diff-sequence@1.0.3
ecmascript@0.4.1
ecmascript-runtime@0.2.8
ejson@1.0.9
es5-shim@4.5.8
fastclick@1.0.9
geojson-utils@1.0.6
hot-code-push@1.0.2
html-tools@1.0.7
htmljs@1.0.7
http@1.1.3
id-map@1.0.5
insecure@1.0.5
jquery@1.11.6
lai:collection-extensions@0.1.4
launch-screen@1.0.8
livedata@1.0.16
logging@1.0.10
meteor@1.1.12
meteor-base@1.0.2
minifier-css@1.1.9
minifier-js@1.1.9
minimongo@1.0.12
mobile-experience@1.0.2
mobile-status-bar@1.0.10
modules@0.5.1
modules-runtime@0.6.1
mongo@1.1.5
mongo-id@1.0.2
npm-mongo@1.4.41
observe-sequence@1.0.9
ordered-dict@1.0.5
pbastowski:angular-babel@1.0.9
promise@0.6.5
random@1.0.7
reactive-dict@1.1.5
reactive-var@1.0.7
reload@1.1.6
retry@1.0.5
routepolicy@1.0.8
session@1.1.3
spacebars@1.0.9
spacebars-compiler@1.0.9
standard-minifier-css@1.0.4
standard-minifier-js@1.0.4
templating-tools@1.0.2
tracker@1.0.11
ui@1.0.9
underscore@1.0.6
url@1.0.7
webapp@1.2.6
webapp-hashing@1.0.7
```

**Comment by kamilkisiela** [comment]
You should try latest version of angular-babel which is `1.3.1`. There was one issue with Meteor 1.3 it's related to your problem :)

**Comment by Deadly0** [comment]
I've update angular-babel to 1.3.1 and now have following errors:
```
Unable to resolve some modules:

  "underscore" in /C/Users/Deadly/AppData/Local/.meteor/packages/angular-meteor-data/1.3.9/web.browser/.npm/package/node_modules/angular-meteor/dist/angular-meteor.js (web.browser)
  "jsondiffpatch" in /C/Users/Deadly/AppData/Local/.meteor/packages/angular-meteor-data/1.3.9/web.browser/.npm/package/node_modules/angular-meteor/dist/angular-meteor.js (web.browser)
  "angular" in /C/Projects/my/meteor1.3-angular/app.js (web.browser)
  "angular-meteor" in /C/Projects/my/meteor1.3-angular/app.js (web.browser)

Consider running: meteor npm install --save underscore jsondiffpatch angular angular-meteor


Unable to resolve some modules:

  "angular" in /C/Projects/my/meteor1.3-angular/app.js (os.windows.x86_32)
  "angular-meteor" in /C/Projects/my/meteor1.3-angular/app.js (os.windows.x86_32)

Consider running: meteor npm install --save angular angular-meteor

W20160329-00:31:29.533(3)? (STDERR) 
W20160329-00:31:29.533(3)? (STDERR) C:\Users\Deadly\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160329-00:31:29.533(3)? (STDERR)                                             throw(ex);
W20160329-00:31:29.533(3)? (STDERR)                                                   ^
W20160329-00:31:29.533(3)? (STDERR) Error: Can't find npm module 'angular'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160329-00:31:29.533(3)? (STDERR)     at Object.Npm.require (C:\Projects\my\meteor1.3-angular\.meteor\local\build\programs\server\boot.js:195:17)
W20160329-00:31:29.534(3)? (STDERR)     at options.fallback (packages\modules-runtime.js:413:18)
W20160329-00:31:29.534(3)? (STDERR)     at require (packages\modules-runtime.js:98:16)
W20160329-00:31:29.534(3)? (STDERR)     at meteorInstall.app.js (app\app.js:9:1)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20160329-00:31:29.534(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:158:9)
W20160329-00:31:29.534(3)? (STDERR)     at require (packages\modules-runtime.js:92:16)
W20160329-00:31:29.534(3)? (STDERR)     at app\app.js:20:1
W20160329-00:31:29.534(3)? (STDERR)     at C:\Projects\my\meteor1.3-angular\.meteor\local\build\programs\server\boot.js:283:10
W20160329-00:31:29.534(3)? (STDERR)     at Array.forEach (native)
W20160329-00:31:29.535(3)? (STDERR)     at Function._.each._.forEach (C:\Users\Deadly\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)

```

**Comment by Deadly0** [comment]
Ok, i've moved angular code to client folder. All my code is:
```
import angular from 'angular';
import 'angular-meteor';

angular.module('socially', ['angular-meteor']);
```

Errors in browser console:
```
modules-runtime.js?hash=939c79d…:95 Uncaught Error: Cannot find module 'angular'require @ modules-runtime.js?hash=939c79d…:95meteorInstall.client.app.js @ app.js:4fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92(anonymous function) @ app.js:4
angular_angular.js?hash=c17a5a9…:83 Uncaught Error: [$injector:modulerr] Failed to instantiate module socially due to:
Error: [$injector:nomod] Module 'socially' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=socially
    at http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:83:12
    at http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:2020:17
    at ensure (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:1944:38)
    at module (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:2018:14)
    at http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:4450:22
    at forEach (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:355:20)
    at loadModules (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:4434:5)
    at createInjector (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:4359:11)
    at doBootstrap (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:1691:20)
    at bootstrap (http://localhost:3000/packages/angular_angular.js?hash=c17a5a9bc4ab8702438c39d764efe4d6334a23e2:1712:12)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=socially&p1=Error%3…r_angular.js%3Fhash%3Dc17a5a9bc4ab8702438c39d764efe4d6334a23e2%3A1712%3A12)
```

**Comment by vivekmago** [comment]
I tried to use and follow the tutorial with meteor 1.3 that was just released but am getting errors. Would be great if someone could confirm when we are likely to get 1.3 support for both client and server modes.

angular_angular.js?hash=c17a5a9…:83 Uncaught Error: [$injector:modulerr] Failed to instantiate module socially due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=angular-meteor

**Comment by capanemaggfc** [comment]
this version has a bug in angular-meteor :/ dont update for now, use the previous version.

**Comment by Urigo** [comment]
Please try `1.3.9_1` and let me know if that works for you

**Comment by Deadly0** [comment]
@Urigo i've updated to ``1.3.9_1`` from Atmosphere and looks like it works. But i still need to install ``pbastowski:angular-babel`` manually becouse ``pbastowski:angular-babel@1.0.9`` not working with ``Meteor@1.3``
Also when i install angular-meteor from npm i just see blank screen without any errors on server or client.

**Comment by Urigo** [comment]
@pbastowski maybe we can publish `pbastowski:angular-babel@1.0.10` that set the dependency below 1.3 and not just 1.2 and above?

**Comment by pbastowski** [comment]
@Urigo 
How would I do that, Uri? Specifically, do I need to add something to package.js? Or, perhaps, do I need to publish different package versions with different versions of Meteor?

**Comment by Urigo** [comment]
@Deadly0 about installing from Npm, if you do that, you will need to use the new setup, as described in the new tutorial (soon also in Socially) - https://www.meteor.com/tutorials/angular/creating-an-app

@pbastowski maybe in the `versionsFrom` option.
I'm not sure if you can specify there "higher than" "lower than" thing, but if you can't, maybe you can do the same in terms of the `api.use` for specific packages

**Comment by pbastowski** [comment]
@Urigo 
`versionsFrom` only applies to Meteor's own internal packages, so, can't use that. And, there is no "lower than" parameter unfortunately.

I will research a bit into into other ways to restrict a package to a specific version.

**Comment by kokokenada** [comment]
Is there an example repository showing typescript, angular and Meteor 1.3?  (Ideally with package/ examples.) I've been struggling all day...

**Comment by kokokenada** [comment]
Thanks @pbastowski for helping me with this example repository https://github.com/kokokenada/tstest2
