### ISSUE TITLE
Stuck on A2 Step 3 Tutorial 

### ISSUE THREAD

**Issue by audan2009** [Urigo/angular-meteor#1372]
I keep getting this error:

W20160605-01:10:01.332(-5)? (STDERR)          
W20160605-01:10:01.333(-5)? (STDERR) /Users/Dan/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160605-01:10:01.333(-5)? (STDERR)            				throw(ex);
W20160605-01:10:01.333(-5)? (STDERR)            				      ^
W20160605-01:10:01.576(-5)? (STDERR) Error: A method named '/parties/insert' is already defined
W20160605-01:10:01.576(-5)? (STDERR)     at packages/ddp-server/livedata_server.js:1548:15
W20160605-01:10:01.576(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160605-01:10:01.576(-5)? (STDERR)     at Server.methods (packages/ddp-server/livedata_server.js:1544:7)
W20160605-01:10:01.576(-5)? (STDERR)     at packages/allow-deny/allow-deny.js:191:24
W20160605-01:10:01.577(-5)? (STDERR)     at [object Object].CollectionPrototype._defineMutationMethods (packages/allow-deny/allow-deny.js:190:5)
W20160605-01:10:01.577(-5)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:226:8)
W20160605-01:10:01.577(-5)? (STDERR)     at meteorInstall.collections.parties.js (collections/parties.ts:3:22)
W20160605-01:10:01.577(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160605-01:10:01.577(-5)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160605-01:10:01.578(-5)? (STDERR)     at collections/parties.ts:3:54
^C                                              

It keeps rebuilding and throwing this error

**Comment by audan2009** [comment]
Problem was Atom auto compiling. Got it work.
