### ISSUE TITLE
angular-templates 1.0.6_1 still breaks using html files from local package in an Meteor 1.2 style app

### ISSUE THREAD

**Issue by blongstreth** [Urigo/angular-meteor#1396]
This bug (#1390) is still showing up in angular-templates version 1.0.6_1 when used with latest version of Meteor 1.3 but in Meteor 1.2 style application with local application packages.  Can this please be updated to work as Meteor 1.2 style application without NPM (meteor-node-stubs), imports, etc...for backwards compatibility?

```
=> Started proxy.                             
=> Started MongoDB.                           
/Users/foo/.meteor/packages/coffeescript/.1.1.4.hibsy4++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: Attempting to combine different files:
{ type: 'js',
  sourcePath: 'client/loading-busy.html',
  servePath: 'node_modules/meteor/foo:loading/client/loading-busy.html',
  installPath: 'node_modules/meteor/foo:loading/client/loading-busy.html',
  deps: { './loading-busy.html!raw': {} },
  lazy: true,
  data: <Buffer 6d 6f 64 75 6c 65 2e 65 78 70 6f 72 74 73 20 3d 20 72 65 71 75 69 72 65 28 22 2e 2f 6c 6f 61 64 69 6e 67 2d 62 75 73 79 2e 68 74 6d 6c 21 72 61 77 22 29 ...>,
  hash: '94fdda38ea14879da6923d3fcb3b73113aa065d3' }
{ type: 'js',
  data: <Buffer 0a 20 20 20 20 20 20 69 66 20 28 4d 65 74 65 6f 72 2e 69 73 53 65 72 76 65 72 29 20 72 65 74 75 72 6e 3b 0a 0a 20 20 20 20 20 20 76 61 72 20 74 65 6d 70 ...>,
  sourcePath: 'client/loading-busy.html',
  targetPath: 'client/loading-busy.html',
  servePath: '/packages/foo_loading/client/loading-busy.html',
  hash: '79cf7fef8e3eaaef87e49559b55741836a3eae79',
  sourceMap: undefined,
  lazy: false,
  bare: false,
  mainModule: false,
  imported: true,
  installPath: 'node_modules/meteor/foo:loading/client/loading-busy.html' }

    at checkProperty (/tools/isobuild/import-scanner.js:293:15)
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:303:5)
    at /tools/isobuild/import-scanner.js:206:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:177:11)
    at /tools/isobuild/compiler-plugin.js:1011:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:982:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:926:8)
    at /tools/isobuild/bundler.js:697:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:688:18)
    at /tools/isobuild/bundler.js:2544:14
    at /tools/isobuild/bundler.js:2633:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/foo/.meteor/packages/meteor-tool/.1.3.5_1.656zhu++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2632:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2525:31)
    at /tools/isobuild/bundler.js:2472:32
    at Object.withCache (/tools/fs/files.js:1445:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2472:16)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by kamilkisiela** [comment]
#1397 should fix it
