### ISSUE TITLE
pbastowski:angular-babel  No metadata files found

### ISSUE THREAD

**Issue by ghevariyaarjun** [Urigo/angular-meteor#1411]
C:\Users\Infizer2\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteo
r\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Infizer2/AppData/Local/.meteor/packages/pbastowski_angular-babel/1.3.6
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:520:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Infizer2\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev
_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:519:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:454:20)
    at C:\tools\packaging\tropohouse.js:598:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:595:20)
    at C:\tools\project-context.js:748:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:747:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:746:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\cli\commands-packages.js:1976:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.func (C:\tools\cli\commands-packages.js:1975:27)
    at C:\tools\cli\main.js:1410:23

any soluation ?

**Comment by pbastowski** [comment]
@ghevariyaarjun 
Please provide a link to your repo, and then I will have a look at the problem for you.

I need this, because the information you provided above is not enough for me to make an assessment of what has gone wrong.

Also, I think you are running Meteor on windows, am I right?

**Comment by ghevariyaarjun** [comment]
yes , i am running on windows 7

my command step by step 

1)   meteor create soc
2)   meteor remove blaze-html-templates ecmascript
3)   meteor npm install --save angular angular-meteor
4)   meteor add  pbastowski:angular-babel

i have command fire 

that time error fetch

**Comment by ghevariyaarjun** [comment]
yes i am used windows

As a meteor project . so , i type

-->  meteor create soci
-->  cd soci
-->  meteor remove blaze-html-templates ecmascript
-->  meteor npm install --save angular angular-meteor
-->  meteor add pbastowski:angular-babel

**Comment by ghevariyaarjun** [comment]
C:\Users\Infizer2\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Infizer2/AppData/Local/.mete
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:520:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Infizer2\AppData\Local\.meteor\packages\m
    at C:\tools\packaging\tropohouse.js:519:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:454:20)
    at C:\tools\packaging\tropohouse.js:598:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse
    at C:\tools\project-context.js:748:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:747:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\ca
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:746:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\cli\commands-packages.js:1976:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.func (C:\tools\cli\commands-packages.js:1975:27)
    at C:\tools\cli\main.js:1410:23


and error fetch .

**Comment by pbastowski** [comment]
The above process works for me on a MacBook with OS X. 

Perhaps it's a problem with Meteor 1.4 on Windows. Unfortunately, I don't actually have a Windows machine to try this on at the moment.

**Comment by leandrogf** [comment]
1. Open the prompt and navigate to path: "C:\Users\[USERNAME]\AppData\Local\.meteor\packages\pbastowski_angular-babel\1.3.6\plugin.compileNGScript.os\npm"
2. Execute "npm uninstall meteor" (Remember that Windows not  allow us delete files in very long paths)
3. Delete folder "C:\Users\[USERNAME]\AppData\Local\.meteor\packages\pbastowski_angular-babel". Execute command "meteor update" in your application. Remember

**Comment by split750** [comment]
works great ! Thank you :-)
