### ISSUE TITLE
Error at meteor startup (inside  static-html-compiler)

### ISSUE THREAD

**Issue by maiardm** [Urigo/angular-meteor#1469]
Hi! i'm trying to run (again) meteor tutorial  (angular version)  of simple-todos app, but now i'm getting back errors messages from "packages/urigo:static-html-compiler/build/src/index.js".

```

C:\>meteor create simple-todos
Created a new Meteor app in 'simple-todos'.

To run your new app:
  cd simple-todos
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn


cd simple-todos
  
C:\simple-todos>meteor npm install

simple-todos@ C:\simple-todos
`-- meteor-node-stubs@0.2.3
  +-- assert@1.3.0
  +-- browserify-zlib@0.1.4
  | `-- pako@0.2.8
  +-- buffer@4.5.1
  | +-- base64-js@1.1.2
  | +-- ieee754@1.1.6
  | `-- isarray@1.0.0
  +-- console-browserify@1.1.0
  | `-- date-now@0.1.4
  +-- constants-browserify@1.0.0
  +-- crypto-browserify@3.11.0
  | +-- browserify-cipher@1.0.0
  | | +-- browserify-aes@1.0.6
  | | | +-- buffer-xor@1.0.3
  | | | `-- cipher-base@1.0.2
  | | +-- browserify-des@1.0.0
  | | | +-- cipher-base@1.0.2
  | | | `-- des.js@1.0.0
  | | |   `-- minimalistic-assert@1.0.0
  | | `-- evp_bytestokey@1.0.0
  | +-- browserify-sign@4.0.0
  | | +-- bn.js@4.11.1
  | | +-- browserify-rsa@4.0.1
  | | +-- elliptic@6.2.3
  | | | +-- brorand@1.0.5
  | | | `-- hash.js@1.0.3
  | | `-- parse-asn1@5.0.0
  | |   +-- asn1.js@4.5.2
  | |   | `-- minimalistic-assert@1.0.0
  | |   +-- browserify-aes@1.0.6
  | |   | +-- buffer-xor@1.0.3
  | |   | `-- cipher-base@1.0.2
  | |   `-- evp_bytestokey@1.0.0
  | +-- create-ecdh@4.0.0
  | | +-- bn.js@4.11.1
  | | `-- elliptic@6.2.3
  | |   +-- brorand@1.0.5
  | |   `-- hash.js@1.0.3
  | +-- create-hash@1.1.2
  | | +-- cipher-base@1.0.2
  | | +-- ripemd160@1.0.1
  | | `-- sha.js@2.4.5
  | +-- create-hmac@1.1.4
  | +-- diffie-hellman@5.0.2
  | | +-- bn.js@4.11.1
  | | `-- miller-rabin@4.0.0
  | |   `-- brorand@1.0.5
  | +-- inherits@2.0.1
  | +-- pbkdf2@3.0.4
  | +-- public-encrypt@4.0.0
  | | +-- bn.js@4.11.1
  | | +-- browserify-rsa@4.0.1
  | | `-- parse-asn1@5.0.0
  | |   +-- asn1.js@4.5.2
  | |   | `-- minimalistic-assert@1.0.0
  | |   +-- browserify-aes@1.0.6
  | |   | +-- buffer-xor@1.0.3
  | |   | `-- cipher-base@1.0.2
  | |   `-- evp_bytestokey@1.0.0
  | `-- randombytes@2.0.3
  +-- domain-browser@1.1.7
  +-- events@1.1.0
  +-- http-browserify@1.7.0
  | +-- Base64@0.2.1
  | `-- inherits@2.0.1
  +-- https-browserify@0.0.1
  +-- os-browserify@0.2.1
  +-- path-browserify@0.0.0
  +-- process@0.11.2
  +-- punycode@1.4.1
  +-- querystring-es3@0.2.1
  +-- readable-stream@2.0.6
  | +-- core-util-is@1.0.2
  | +-- inherits@2.0.1
  | +-- isarray@1.0.0
  | +-- process-nextick-args@1.0.6
  | `-- util-deprecate@1.0.2
  +-- stream-browserify@2.0.1
  | `-- inherits@2.0.1
  +-- string_decoder@0.10.31
  +-- timers-browserify@1.4.2
  +-- tty-browserify@0.0.0
  +-- url@0.11.0
  | +-- punycode@1.3.2
  | `-- querystring@0.2.0
  +-- util@0.10.3
  | `-- inherits@2.0.1
  `-- vm-browserify@0.0.4
    `-- indexof@0.0.1

C:\simple-todos>meteor remove blaze-html-templates

Changes to your project's package version selections:

blaze-html-templates   removed from your project
caching-compiler       removed from your project
caching-html-compiler  removed from your project
templating             removed from your project
templating-compiler    removed from your project
templating-runtime     removed from your project
templating-tools       removed from your project

blaze-html-templates: removed dependency

C:\simple-todos>meteor add angular-templates

Changes to your project's package version selections:

angular-templates           added, version 1.0.9
caching-compiler            added, version 1.0.6
urigo:static-html-compiler  added, version 0.1.8

C:\simple-todos>meteor npm install --save angular angular-meteor

angular-templates: Compile angular templates into the template cache
simple-todos@ C:\simple-todos
+-- angular@1.5.8
`-- angular-meteor@1.3.11
  +-- jsondiffpatch@0.1.43
  | `-- chalk@0.5.1
  |   +-- ansi-styles@1.1.0
  |   +-- escape-string-regexp@1.0.5
  |   +-- has-ansi@0.1.0
  |   | `-- ansi-regex@0.2.1
  |   +-- strip-ansi@0.3.0
  |   `-- supports-color@0.2.0
  `-- underscore@1.8.3


C:\simple-todos>meteor -v
[[[[[ C:\simple-todos ]]]]]

=> Started proxy.
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: angular-templates@1.0.9
Local package version is up-to-date: autopublish@1.0.7
Local package version is up-to-date: autoupdate@1.2.11
Local package version is up-to-date: babel-compiler@6.13.0
Local package version is up-to-date: babel-runtime@0.1.13
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.1.9
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.0.11
Local package version is up-to-date: caching-compiler@1.0.6
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.4
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.2.9
Local package version is up-to-date: ddp-common@1.2.7
Local package version is up-to-date: ddp-server@1.2.10
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: ecmascript@0.5.9
Local package version is up-to-date: ecmascript-runtime@0.3.15
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.1.8
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: insecure@1.0.7
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: launch-screen@1.0.12
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: logging@1.1.16
Local package version is up-to-date: meteor@1.6.0
Local package version is up-to-date: meteor-base@1.0.4
Local package version is up-to-date: minifier-css@1.2.15
Local package version is up-to-date: minifier-js@1.2.15
Local package version is up-to-date: minimongo@1.0.18
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.13
Local package version is up-to-date: modules@0.7.7
Local package version is up-to-date: modules-runtime@0.7.7
=> Started MongoDB.
Local package version is up-to-date: mongo@1.1.14
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: npm-mongo@2.2.11_2
Local package version is up-to-date: observe-sequence@1.0.14
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: promise@0.8.8
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: shell-server@0.2.1
Local package version is up-to-date: spacebars@1.0.13
Local package version is up-to-date: spacebars-compiler@1.0.13
Local package version is up-to-date: standard-minifier-css@1.3.2
Local package version is up-to-date: standard-minifier-js@1.2.1
Local package version is up-to-date: tracker@1.1.1
Local package version is up-to-date: ui@1.0.12
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: urigo:static-html-compiler@0.1.8
Local package version is up-to-date: url@1.0.11
Local package version is up-to-date: webapp@1.3.12
Local package version is up-to-date: webapp-hashing@1.0.9
=> Errors prevented startup:

   While processing files with angular-templates (for target web.browser):
   native: main.html has wrong layout
   at Error (native)
   at packages/urigo:static-html-compiler/build/src/index.js:34:27
   at Array.forEach (native)
   at StaticHtmlCompiler.processFilesForTarget (packages/urigo:static-html-compiler/build/src/index.js:19:15)


=> Your application has errors. Waiting for file change.

```

I tried also run **socially tutorial**, with similar results before this.

I'm running the original code from tutorial files (no changes introduced), on a simple step by step proceeding.

A few days ago, **todos tutorial** runned normally, without any problems.

"main.html" (following), does not seems to have any problems

```
<head>
  <title>simple-todos</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
  {{> info}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>

<template name="info">
  <h2>Learn Meteor!</h2>
  <ul>
    <li><a href="https://www.meteor.com/try" target="_blank">Do the Tutorial</a></li>
    <li><a href="http://guide.meteor.com" target="_blank">Follow the Guide</a></li>
    <li><a href="https://docs.meteor.com" target="_blank">Read the Docs</a></li>
    <li><a href="https://forums.meteor.com" target="_blank">Discussions</a></li>
  </ul>
</template>

```

**Comment by Urigo** [comment]
@maiardm that tutorial is not updated and I'm not recommending to use that, please try the Socially tutorial which is updated - https://www.angular-meteor.com/tutorials/socially/angular1/bootstrapping

**Comment by charly37** [comment]
Exact same issue today. 

```
> [charles@555555 ~]$ meteor create simple
> Created a new Meteor app in 'simple'.
> 
> To run your new app:
>   cd simple
>   meteor
> 
> If you are new to Meteor, try some of the learning resources here:
>   https://www.meteor.com/learn
> 
> meteor create --bare to create an empty app.
> meteor create --full to create a scaffolded app.
> 
> [charles@555555 ~]$ cd simple/
> [charles@555555 simple]$ meteor npm install
> [charles@555555 simple]$ meteor
> [[[[[ ~/simple ]]]]]
> 
> => Started proxy.
> => Started MongoDB.
> => Started your app.
> 
> => App running at: http://localhost:3000/
> ^C
> [charles@555555 simple]$ meteor remove blaze-html-templates
> 
> Changes to your project's package version selections:
> 
> blaze-html-templates   removed from your project
> caching-compiler       removed from your project
> caching-html-compiler  removed from your project
> templating             removed from your project
> templating-compiler    removed from your project
> templating-runtime     removed from your project
> templating-tools       removed from your project
> 
> blaze-html-templates: removed dependency
> [charles@555555 simple]$ meteor add angular-templates
> 
> Changes to your project's package version selections:
> 
> angular-templates           added, version 1.0.9
> caching-compiler            added, version 1.1.9
> urigo:static-html-compiler  added, version 0.1.8
> 
> 
> angular-templates: Compile angular templates into the template cache
> [charles@555555 simple]$ meteor npm install --save angular angular-meteor
> simple@ /home/charles/simple
> ├── angular@1.6.3
> └─┬ angular-meteor@1.3.11
>   ├─┬ jsondiffpatch@0.1.43
>   │ └─┬ chalk@0.5.1
>   │   ├── ansi-styles@1.1.0
>   │   ├── escape-string-regexp@1.0.5
>   │   ├─┬ has-ansi@0.1.0
>   │   │ └── ansi-regex@0.2.1
>   │   ├── strip-ansi@0.3.0
>   │   └── supports-color@0.2.0
>   └── underscore@1.8.3
> 
> [charles@555555 simple]$ meteor
> [[[[[ ~/simple ]]]]]
> 
> => Started proxy.
> => Started MongoDB.
> => Errors prevented startup:
> 
>    While processing files with angular-templates (for target web.browser):
>    native: main.html has wrong layout
>    at Error (native)
>    at packages/urigo:static-html-compiler/build/src/index.js:34:27
>    at Array.forEach (native)
>    at StaticHtmlCompiler.processFilesForTarget (packages/urigo:static-html-compiler/build/src/index.js:19:15)
> 
> 
> => Your application has errors. Waiting for file change.
```

The tutorial is the first one on the 3 available on the tutorial page : https://www.meteor.com/tutorials
I would except it to be working and if it is not supported it should be removed.

**Comment by Paaarth** [comment]
I am still getting this error 


=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with angular-templates (for target web.browser):
   native: main.html has wrong layout
   at Error (native)
   at packages/urigo:static-html-compiler/build/src/index.js:34:27
   at Array.forEach (native)
   at StaticHtmlCompiler.processFilesForTarget
   (packages/urigo:static-html-compiler/build/src/index.js:19:15)


=> Your application has errors. Waiting for file change.

**Comment by erudstam** [comment]
Same error. Please Help!

=> Errors prevented startup:

   While processing files with urigo:static-templates (for target web.browser):
   native: main.html has wrong layout
   at Error (native)
   at packages/urigo:static-html-compiler/build/src/index.js:34:27
   at Array.forEach (native)
   at StaticHtmlCompiler.processFilesForTarget
   (packages/urigo:static-html-compiler/build/src/index.js:19:15)

**Comment by gustawdaniel** [comment]
Try:

    meteor remove static-html

and install proper html processor like blaze, react or angular...
