### ISSUE TITLE
Unit testing error

### ISSUE THREAD

**Issue by clouchtibat** [Urigo/angular-meteor#153]
I've got an error in my unit tests with the new version of angular-meteor. The tests worked before and the error is the same for each of my tests.
I use sanjo:jasmine package and the latest version of angular-mocks.

Here is the stacktrace :

    Error: [$injector:unpr] Unknown provider: $meteorMethodsProvider <- $meteorMethods <- authorization
    http://errors.angularjs.org/1.3.8/$injector/unpr?p0=%24meteorMethodsProvider%20%3C-%20%24meteorMethods%20%3C-%20authorization
        at http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:92:12
        at http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4023:19
        at Object.getService [as get] (http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4170:39)
        at http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4028:45
        at getService (http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4170:39)
        at Object.invoke (http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4202:13)
        at Object.enforcedReturnValue [as $get] (http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4064:37)
        at Object.invoke (http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4211:17)
        at http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4029:37
       at getService (http://localhost:9876/base/.meteor/local/build/programs/web.browser/packages/urigo_angular.js:4170:39)

Any idea about that?

**Comment by netanelgilad** [comment]
It's hard to know without seeing your code, so if you have it in a repo we can take a look.
I'm guessing you have a service called authorization that uses $meteorMethods, but maybe the angular module you are testing doesn't have a dependency on 'angular-meteor'?
That is the only guess I can think of without seeing more code...

**Comment by clouchtibat** [comment]
I just forgot to add the angular-meteor dependency... I'm so ashamed...

Thanks.
