### ISSUE TITLE
Using angular-compilers in Meteor 1.5.x

### ISSUE THREAD

**Issue by filosof86** [Urigo/angular-meteor#1879]
Hi,

Meteor: v1.5.4.1
Angular: v4.4.6
Compilers: version 0.2.5

Description of the issue: 
Using angular compilers in meteor 1.5.4.1 is constantly giving the following error:  
=> Errors prevented startup: While loading plugin `Angular Compilers` from package `angular-compilers`:
   vm.js:24:10: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

STR: 

1. Create meteor-angular application
2. Remove the previous compilers with: meteor remove angular2-compilers
2. Add new compilers with: meteor add angular-compilers
3. meteor run

The full text of the error along with the package versions can be found below.

I would like to continue using Meteor 1.5 for now, so the question:
Is it possible to use the mentioned package with Meteor 1.5.x or I need to update meteor and/or angular versions to the latest ones?

Thank you in advance.

error: 

```bash
=> Errors prevented startup:                  
   
   While loading plugin `Angular Compilers` from package `angular-compilers`:
   vm.js:24:10: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
   at Object.exports.createScript (vm.js:24:10)
   at /tools/fs/files.js:1154:34
   at Function.time (/tools/tool-env/profile.js:305:10)
   at Object.files.runJavaScript (/tools/fs/files.js:1092:18)
   at /tools/isobuild/bundler.js:1973:15
   at Array.forEach (native)
   at Function._.each._.forEach
   (/home/filosof/.meteor/packages/meteor-tool/.1.5.4_1.6s835x.g0msh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at JsImage.load (/tools/isobuild/bundler.js:1858:7)
   at /tools/isobuild/isopack.js:536:16
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/isopack.js:526:20
   at Function._.each._.forEach
   (/home/filosof/.meteor/packages/meteor-tool/.1.5.4_1.6s835x.g0msh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at [object Object].ensurePluginsInitialized (/tools/isobuild/isopack.js:514:7)
   at /tools/isobuild/compiler.js:382:16
   at Array.forEach (native)
   at /tools/isobuild/compiler.js:381:26
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/compiler.js:377:16
   at /tools/isobuild/compiler.js:184:28
   at Object.withCache (/tools/fs/files.js:1686:12)
   at /tools/isobuild/compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach
   (/home/filosof/.meteor/packages/meteor-tool/.1.5.4_1.6s835x.g0msh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at Object.compile (/tools/isobuild/compiler.js:178:5)
   at /tools/isobuild/bundler.js:2956:24
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at bundle (/tools/isobuild/bundler.js:2899:31)
   at /tools/isobuild/bundler.js:2846:32
   at Object.withCache (/tools/fs/files.js:1686:12)
   at Object.exports.bundle (/tools/isobuild/bundler.js:2846:16)
   at /tools/runners/run-app.js:583:36
   at Function.run (/tools/tool-env/profile.js:490:12)
   at bundleApp (/tools/runners/run-app.js:582:34)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:626:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:885:28)
   at /tools/runners/run-app.js:412:12
```

package.json:

```javascript

  "devDependencies": {
    "@angular/compiler-cli": "4.4.6",
    "@types/bluebird": "3.5.18",
    "@types/chai": "3.5.2",
    "@types/core-js": "0.9.36",
    "@types/meteor": "1.4.5",
    "@types/mocha": "2.2.42",
    "chai": "3.5.0",
    "chai-spies": "0.7.1",
    "meteor-node-stubs": "0.2.11",
    "node-sass": "4.5.3",
    "ts-node": "3.3.0",
    "typescript": "2.5.3"
  },
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@types/node": "8.0.47",
    "amazing-time-picker": "1.1.8",
    "angular2-meteor": "0.8.0",
    "angular2-meteor-polyfills": "0.2.0",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "babel-runtime": "6.26.0",
    "bcrypt": "1.0.3",
    "bluebird": "3.5.1",
    "hammerjs": "2.0.8",
    "ldapauth-fork": "4.0.2",
    "ldapjs": "1.0.1",
    "meteor-rxjs": "0.4.7",
    "moment": "2.18.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "zone.js": "0.8.17"
  }
```
meteor package versions:

```bash
accounts-base@1.3.4
accounts-password@1.4.0
allow-deny@1.0.9
angular-compilers@0.2.5
angular-html-compiler@0.2.5
angular-scss-compiler@0.2.5
angular-typescript-compiler@0.2.7_1
audit-argument-checks@1.0.7
autoupdate@1.3.12
babel-compiler@6.20.0
babel-runtime@1.0.1
barbatus:typescript@0.6.11
barbatus:typescript-compiler@0.9.11
barbatus:typescript-runtime@1.0.2
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-tools@1.0.10
boilerplate-generator@1.2.0
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
chfritz:easycron@0.0.4
coffeescript@1.12.7_1
coffeescript-compiler@1.12.7_1
ddp@1.3.1
ddp-client@2.1.3
ddp-common@1.2.9
ddp-rate-limiter@1.0.7
ddp-server@2.0.2
deps@1.0.12
diff-sequence@1.0.7
dispatch:mocha-phantomjs@0.1.9
dispatch:phantomjs-tests@0.0.7
dynamic-import@0.1.3
ecmascript@0.8.3
ecmascript-runtime@0.4.1
ecmascript-runtime-client@0.4.3
ecmascript-runtime-server@0.4.1
ejson@1.0.14
email@1.2.3
es5-shim@4.6.15
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
hwillson:stub-collections@1.0.3
id-map@1.0.9
jquery@1.11.10
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.1.1
logging@1.1.17
meteor@1.7.2
meteor-base@1.1.0
mikowals:batch-insert@1.1.14
minifier-css@1.2.16
minifier-js@2.1.4
minimongo@1.3.2
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.10.0
modules-runtime@0.8.0
mongo@1.2.3
mongo-dev-server@1.0.1
mongo-id@1.0.6
npm-bcrypt@0.9.3
npm-mongo@2.2.30
observe-sequence@1.0.16
ordered-dict@1.0.9
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.9.0
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.1.9
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.4
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.3.5
standard-minifier-js@2.1.2
templating@1.3.2
templating-compiler@1.3.2
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.3
underscore@1.0.10
url@1.1.0
webapp@1.3.19
webapp-hashing@1.0.9
xolvio:cleaner@0.3.1
```

**Comment by jerradpatch** [comment]
I am no expert, but maybe your version of node is too old to compile the package?

**Comment by filosof86** [comment]
@jerradpatch, yes, it can be the reason, thank you.
Anyway, I've updated the application to 1.6.x so this issue can be closed.

**Comment by ardatan** [comment]
Thank you!
