### ISSUE TITLE
Build fails for architecture os.linux.x86_64 on windows

### ISSUE THREAD

**Issue by gjr-qm** [Urigo/angular-meteor#1881]
### How to reproduce

- On a Windows 10 computer clone angular-meteor-base repository (current Meteor version 1.6)
- Enter dir and do `meteor npm install`
- Try to build the app with `meteor build <outdir> --server-only --architecture os.linux.x86_64` 

Build fails with the error:
```
Loading NgModules!: 0.392ms
{ Error: File to read not found or unreadable: C:/Work/angular-meteor-base/C:/Work/angular-meteor-base/client/imports/app/todo-list/todo-list.scss
    at Object.module.exports.renderSync (C:\Users\username\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass\lib\index.js:439:16)
    at AngularScssCompiler.compileFile (packages/angular-scss-compiler/index.js:24:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.compiler._host.loadResource.filePath [as loadResource] (packages/angular-typescript-compiler/index.js:279:45)
    at Object.get (C:\Users\username\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler_factory.js:78:306)
....
```
Important part here is the doubling of the directory for the css file **C:/Work/angular-meteor-base/C:/Work/angular-meteor-base**. Seems like the compiler doubles the path.

### Versions

- Windows 10
- Meteor 1.6.1 installed, angular-meteor-base uses version 1.6 (
- angular-compilers@0.2.8_1
- angular-html-compiler@0.2.8
- angular-scss-compiler@0.2.8
- angular-typescript-compiler@0.2.8_1

### Behavior

- Expected: successful build
- Actual: Error above

My own applicaties (with a few other Meteor sub-versions) show the same behavior. I tried to locate the source where the error occurs, but had to face that I don't know exactly which files are used when compiling...

**Comment by Urigo** [comment]
today we've released new versions for `angular-compilers` with a few fixes and to support the latest Meteor 1.6.1, thanks to the great work of @ardatan !
Let us now if that solves your problem and everything works as expected.
thank you
