### ISSUE TITLE
angular compiler targets different version of babel compiler

### ISSUE THREAD

**Issue by jerradpatch** [Urigo/angular-meteor#1891]
Meteor wont let me install angular-compilers with Meteor 1.6.1

$ git clone https://github.com/Urigo/angular-meteor.git
$ cd ./examples/MeteorCLI/bare
$ meteor npm install
$ meteor run

Error:

While selecting package versions:
error: Conflict: Constraint babel-compiler@6.24.7 is not satisfied by babel-compiler 7.0.5.
Constraints on package "babel-compiler":
* babel-compiler@~7.0.0 <- top level
* babel-compiler@7.0.0 <- ecmascript 0.10.5
* babel-compiler@7.0.0 <- minifier-js 2.3.3 <- standard-minifier-js 2.3.2
* babel-compiler@7.0.0 <- standard-minifier-js 2.3.2
* babel-compiler@6.24.7 <- angular-typescript-compiler 0.2.9_5 <- angular-compilers 0.2.9_2

Angular Compiler Version:
angular-compilers 0.2.9_2

Other package Versions:

I am trying to compile the code from here 
https://github.com/Urigo/angular-meteor/blob/master/examples/MeteorCLI/bare

ecmascript             0.10.5  Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.7.3  Shims and polyfills to improve ECMAScript 5 support
meteor-base            1.3.0  Packages that every Meteor app needs
mobile-experience      1.0.5  Packages for a great mobile user experience
mongo                  1.4.5  Adaptor for using MongoDB and Minimongo over DDP
reactive-var           1.0.11  Reactive variable
shell-server           0.3.1  Server-side component of the `meteor shell` command.
standard-minifier-css  1.4.1  Standard css minifier used with Meteor apps by default.
standard-minifier-js   2.3.2  Standard javascript minifiers used with Meteor apps by default.
static-html            1.2.2  Define static page content in .html files
tracker                1.1.3  Dependency tracker to allow reactive callbacks

**Comment by ardatan** [comment]
Thank you for your post. We haven’t published the atmosphere packages yet.
You can use packages locally bu using METEOR_PACKAGE_DIRS=packagespath environment variable.

**Comment by ardatan** [comment]
We just released the new version of the packages. You can update the packages by running;
`meteor update --all-packages --allow-incompatible-update`
Please let us know if the issue still appears.

**Comment by bouchepat** [comment]
Still getting the same error:

```
C:\Users\Patrick\Meteor\zeteor-2>meteor update --all-packages --allow-incompatible-update
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint babel-compiler@6.19.2 is not satisfied by babel-compiler 7.0.5.
Constraints on package "babel-compiler":
* babel-compiler@~7.0.0 <- top level
* babel-compiler@7.0.0 <- ecmascript 0.10.5
* babel-compiler@6.19.2 <- abernix:standard-minifier-js 2.1.0
* babel-compiler@6.19.2 <- abernix:minifier-js 2.1.0 <- abernix:standard-minifier-js 2.1.0
* babel-compiler@7.0.0 <- angular-typescript-compiler 0.2.9_7 <- angular-compilers 0.2.9_3
```

**Comment by pedrolucasoliva** [comment]
I used `meteor update -all-packeges ` and it updated like a charm

**Comment by ardatan** [comment]
@bouchepat I don’t think it is about angular-compilers. It looks like the conflict is between Meteor’s core packages and your custom minifiers. Could you minifiers and try again?

**Comment by bouchepat** [comment]
I changed the abernix:standard-minifier-js package to the standard-minifier-js, I'm getting the following error:

Thanks for the help by the way!

```
C:\Users\Patrick\Meteor\zeteor-2>meteor update --all-packages --allow-incompatible-update
C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, unlink 'C:\Users\Patrick\AppData\Local\.meteor\packages\angular-compilers\0.2.9_2\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass-garbage-135kga1.9rlc-garbage-8a78uv.kjgc3\vendor\win32-x64-57\binding.node'
 => awaited here:
    at Promise.await (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Object.files.rm_recursive.path [as rm_recursive] (C:\tools\fs\files.js:316:7)
    at Object.files.renameDirAlmostAtomically.Profile [as renameDirAlmostAtomically] (C:\tools\fs\files.js:1012:13)
    at C:\tools\isobuild\meteor-npm.js:401:11
    at Array.forEach (<anonymous>)
    at Object.rebuildIfNonPortable (C:\tools\isobuild\meteor-npm.js:376:17)
    at _.each (C:\tools\isobuild\bundler.js:423:19)
    at Function._.each._.forEach (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at Function.readDirsFromJSON (C:\tools\isobuild\bundler.js:422:9)
    at C:\tools\isobuild\bundler.js:2308:34
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Function.readFromDisk (C:\tools\isobuild\bundler.js:2300:7)
    at Object.readJsImage (C:\tools\isobuild\bundler.js:3237:18)
    at C:\tools\isobuild\isopack.js:872:28
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:869:7)
    at Isopack.initFromPath (C:\tools\isobuild\isopack.js:803:17)
    at C:\tools\isobuild\isopack-cache.js:286:23
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Profile.time (C:\tools\isobuild\isopack-cache.js:272:24)
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:262:15)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\Patrick\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24)
    at C:\tools\project-context.js:847:25
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:846:18)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18)
    at Profile.run (C:\tools\project-context.js:267:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:266:13)
    at C:\tools\cli\commands-packages.js:1597:20
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:275:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1596:8)
    at Command.func (C:\tools\cli\commands-packages.js:1670:29)
    at C:\tools\cli\main.js:1523:15
```

**Comment by ardatan** [comment]
I don’t think it is due to ‘angular-compilers’ as well. 
Try running command prompt as admin or restarting your computer etc. I am using Ubuntu Bash on Windows, and Meteor on it, because Meteor CLI on Windows works weird sometimes.
You can see the similar issue;
https://github.com/meteor/meteor/issues/8139

**Comment by bouchepat** [comment]
Thanks @ardatan, ran the command on a native window command prompt with admin privileges worked.

**Comment by ardatan** [comment]
Your welcome! Thank you for the collaboration.
