### ISSUE TITLE
AngularCLI does not work

### ISSUE THREAD

**Issue by mfechner** [Urigo/angular-meteor#1936]
I tested it on Windows 10 with meteor 1.7.0.3 installed.
To reproduce it, just clone this repo, then go to folder `examples\AngularCLI` and execute:
```
npm install
npm run api
```

You will see the following error message:
```
C:\git\github.com\angular-meteor\examples\AngularCLI>npm run api

> angular-cli-meteor@0.0.0 api C:\git\github.com\angular-meteor\examples\AngularCLI
> cd api && meteor run

[[[[[ C:\git\github.com\angular-meteor\examples\AngularCLI\api ]]]]]

=> Started proxy.
C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected token . in JSON at position 0
    at JSON.parse (<anonymous>)
    at makeOptimistic (C:\tools\fs\optimistic.js:247:17)
    at wrap.makeCacheKey (C:\tools\fs\optimistic.js:25:15)
    at reallyRecompute (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\entry.js:301:28)
    at recomputeIfDirty (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\entry.js:259:12)
    at Entry.recompute (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\entry.js:87:10)
    at optimistic (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\index.js:82:23)
    at MeteorConfig._ensureInitialized (C:\tools\project-context.js:1617:20)
    at MeteorConfig.get (C:\tools\project-context.js:1631:23)
    at MeteorConfig._getEntryModulesByArch (C:\tools\project-context.js:1674:36)
    at MeteorConfig.getMainModulesByArch (C:\tools\project-context.js:1646:17)
    at PackageSource.initFromAppDir (C:\tools\isobuild\package-source.js:853:35)
    at C:\tools\isobuild\bundler.js:3004:19
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:3000:31)
    at files.withCache (C:\tools\isobuild\bundler.js:2947:32)
    at Object.withCache (C:\tools\fs\files.js:1710:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2947:16)
    at Profile.run (C:\tools\runners\run-app.js:579:36)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:578:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-cli-meteor@0.0.0 api: `cd api && meteor run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-cli-meteor@0.0.0 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\idefix\AppData\Roaming\npm-cache\_logs\2018-07-14T09_19_41_924Z-debug.log
```
Is this problem maybe be related to this: https://github.com/meteor/meteor/issues/9995

**Comment by ardatan** [comment]
I think the error is related to your installation. Please uninstall and install again, and open a new issue if the error still shows up.
As I look the error stack trace, I couldn't see any file or module that is related to `angular-meteor`, so it'd better if you search more on the Internet.
