### ISSUE TITLE
AngularCLI example does not work on Windows

### ISSUE THREAD

**Issue by mfechner** [Urigo/angular-meteor#1937]
Referring to #1936 I did the following using an admin console:
```
choco uninstall -y meteor
choco install -y meteor
```
Delete the node_modules folder in the `examples\AngularCLI` directory.
Now using a standard command prompt in `examples\AngularCLI`:
```
npm install
```
which shows:
```
npm install

> node-sass@4.9.2 install C:\git\github.com\angular-meteor\examples\AngularCLI\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\idefix\AppData\Roaming\npm-cache\node-sass\4.9.2\win32-x64-64_binding.node

> node-sass@4.9.2 postinstall C:\git\github.com\angular-meteor\examples\AngularCLI\node_modules\node-sass
> node scripts/build.js

Binary found at C:\git\github.com\angular-meteor\examples\AngularCLI\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.8 postinstall C:\git\github.com\angular-meteor\examples\AngularCLI\node_modules\@angular\cli
> node ./bin/ng-update-message.js


> angular-cli-meteor@0.0.0 postinstall C:\git\github.com\angular-meteor\examples\AngularCLI
> npm run client-bundle


> angular-cli-meteor@0.0.0 client-bundle C:\git\github.com\angular-meteor\examples\AngularCLI
> meteor-client bundle -s api

Created a new Meteor app in 'C:\Users\idefix\AppData\Local\Temp\tmp-269802gzyvvidp7Da'.

To run your new app:
  cd C:\Users\idefix\AppData\Local\Temp\tmp-269802gzyvvidp7Da
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials

To start with a different app template, try one of the following:

  meteor create --bare    # to create an empty app
  meteor create --minimal # to create an app with as few Meteor packages as possible
  meteor create --full    # to create a more complete scaffolded app

up to date in 1.841s
[+] no known vulnerabilities found [602 packages audited]


Changes to your project's package version selections:

autopublish                   removed from your project
barbatus:typescript           added, version 0.7.0
barbatus:typescript-compiler  added, version 0.10.0
barbatus:typescript-runtime   added, version 1.1.0
blaze                         removed from your project
blaze-html-templates          removed from your project
blaze-tools                   removed from your project
caching-compiler              removed from your project
caching-html-compiler         removed from your project
deps                          removed from your project
html-tools                    removed from your project
htmljs                        removed from your project
insecure                      removed from your project
jquery                        removed from your project
observe-sequence              removed from your project
spacebars                     removed from your project
spacebars-compiler            removed from your project
templating                    removed from your project
templating-compiler           removed from your project
templating-runtime            removed from your project
templating-tools              removed from your project
ui                            removed from your project


WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1204 packages from 1297 contributors and audited 22592 packages in 149.258s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Next did a `npm run api`:
```
> angular-cli-meteor@0.0.0 api C:\git\github.com\angular-meteor\examples\AngularCLI
> cd api && meteor run

[[[[[ C:\git\github.com\angular-meteor\examples\AngularCLI\api ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected token . in JSON at position 0
    at JSON.parse (<anonymous>)
    at makeOptimistic (C:\tools\fs\optimistic.js:247:17)
    at wrap.makeCacheKey (C:\tools\fs\optimistic.js:25:15)
    at reallyRecompute (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\entry.js:301:28)
    at recomputeIfDirty (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\entry.js:259:12)
    at Entry.recompute (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\entry.js:87:10)
    at optimistic (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\index.js:82:23)
    at MeteorConfig._ensureInitialized (C:\tools\project-context.js:1617:20)
    at MeteorConfig.get (C:\tools\project-context.js:1631:23)
    at MeteorConfig._getEntryModulesByArch (C:\tools\project-context.js:1674:36)
    at MeteorConfig.getMainModulesByArch (C:\tools\project-context.js:1646:17)
    at PackageSource.initFromAppDir (C:\tools\isobuild\package-source.js:853:35)
    at C:\tools\isobuild\bundler.js:3004:19
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:3000:31)
    at files.withCache (C:\tools\isobuild\bundler.js:2947:32)
    at Object.withCache (C:\tools\fs\files.js:1710:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2947:16)
    at Profile.run (C:\tools\runners\run-app.js:579:36)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:578:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-cli-meteor@0.0.0 api: `cd api && meteor run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-cli-meteor@0.0.0 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\idefix\AppData\Roaming\npm-cache\_logs\2018-07-15T14_19_13_459Z-debug.log

```

**Comment by ardatan** [comment]
As I said before, this error is related to core of meteor; not `angular-meteor`. You can easily see that there is no files related to `angular-meteor` in your error trace. 
`angular-meteor` runs on compile phase while your error is thrown on bundle phase.

**Comment by mfechner** [comment]
I thought that the example has a running version, maybe the example should be downgraded to a version running and upgrade it later if the bug is fixed upstream?

**Comment by ardatan** [comment]
You can downgrade the version by yourself, because it is not related to `angular-meteor`.
