### ISSUE TITLE
Example AngularCLI does not work (cannot run `npm run api`)

### ISSUE THREAD

**Issue by mfechner** [Urigo/angular-meteor#1943]
I just wanted to test the AngularCLI which could be found in `examples/AngularCLI` but if I try to start `npm run api`I see the following error message:
```
W20180808-17:19:08.365(2)? (STDERR) /Volumes/HDD/Users/idefix/git/github/angular-meteor/examples/AngularCLI/api/.meteor/local/build/programs/server/boot.js:475
W20180808-17:19:08.365(2)? (STDERR) }).run();
W20180808-17:19:08.366(2)? (STDERR)    ^
W20180808-17:19:08.366(2)? (STDERR) 
W20180808-17:19:08.366(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180808-17:19:08.366(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180808-17:19:08.366(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180808-17:19:08.367(2)? (STDERR)     at Object.require (/Volumes/HDD/Users/idefix/git/github/angular-meteor/examples/AngularCLI/api/.meteor/local/build/programs/server/boot.js:288:32)
W20180808-17:19:08.367(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180808-17:19:08.367(2)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180808-17:19:08.367(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180808-17:19:08.367(2)? (STDERR)     at livedata_connection.js (/Volumes/HDD/Users/idefix/git/github/angular-meteor/examples/AngularCLI/api/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180808-17:19:08.367(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180808-17:19:08.368(2)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180808-17:19:08.368(2)? (STDERR)     at require (packages/modules-runtime.js:244:21)
=> Exited with code: 1

```
To reproduce it (tested on a MACOSX) do just clone this repository and then do:
```
cd examples/AngularCLI
npm i
npm run api
```

**Comment by mfechner** [comment]
I already tried the following, but it does not help:
```
cd api
meteor remove barbatus:typescript
meteor add angular-compilers
cd ..
npm i @angular/compiler @angular/compiler-cli

```

**Comment by ardatan** [comment]
Not related to `angular-meteor`. Please see 
https://github.com/meteor/meteor/issues/10128
