### ISSUE TITLE
examples/AngularCLI `npm run api` crashes with `Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'`

### ISSUE THREAD

**Issue by KeithGillette** [Urigo/angular-meteor#1946]
### When reporting a bug, please be sure to include the following:

Presumably related to the breaking change in `@babel/runtime@7.0.0-beta.56` noted in the [Meteor@1.7.0.4 release notes](https://github.com/meteor/meteor/blob/devel/History.md#v1704-2018-08-07), the following error occurs when executing `npm run api` in the `examples/AngularCLI` directory after an `npm install`. Pinning `"@babel/runtime": "7.0.0-beta.55"` in `package.json` corrects the problem.

```
W20180809-09:57:33.255(-4)? (STDERR) /Users/keith.gillette/Code/angular-meteor/examples/AngularCLI/api/.meteor/local/build/programs/server/boot.js:475
W20180809-09:57:33.324(-4)? (STDERR) }).run();
W20180809-09:57:33.324(-4)? (STDERR)    ^
W20180809-09:57:33.324(-4)? (STDERR) 
W20180809-09:57:33.324(-4)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180809-09:57:33.325(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180809-09:57:33.325(-4)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180809-09:57:33.325(-4)? (STDERR)     at Object.require (/Users/keith.gillette/Code/angular-meteor/examples/AngularCLI/api/.meteor/local/build/programs/server/boot.js:288:32)
W20180809-09:57:33.325(-4)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:604:18)
W20180809-09:57:33.325(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180809-09:57:33.325(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180809-09:57:33.325(-4)? (STDERR)     at livedata_connection.js (/Users/keith.gillette/Code/angular-meteor/examples/AngularCLI/api/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180809-09:57:33.325(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180809-09:57:33.325(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180809-09:57:33.326(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
=> Exited with code: 1
```

**Comment by ardatan** [comment]
Thank you for contribution! 
Fixed after commit;
https://github.com/Urigo/angular-meteor/commit/ab9f5830d78f3a0eefaa227ffae29cbca411f7fd
