### ISSUE TITLE
Compiling undefined with meteor-babel without a cache

### ISSUE THREAD

**Issue by georgyberdyshev** [Urigo/angular-meteor#1958]
Hello @ardatan,

there is an issue when using AOT w/ Rollup: "Compiling undefined with meteor-babel without a cache"

See for more information:
https://github.com/meteor/meteor/issues/10236#issuecomment-427048932
https://github.com/Urigo/angular-meteor/pull/1927#issuecomment-442387358

Reproduction:
cd examples/MeteorCLI/bare
meteor npm install
AOT=1 ROLLUP=1 meteor build ./.meteor/build-aot-rollup

```
Compiling undefined with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/angular-meteor-sourcecode/examples/MeteorCLI/bare/.meteor/local/isopacks/angular-compilers/plugin.Angular_Compilers.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:79:15)
    at Object.compile (packages/babel-compiler.js:44:29)
    at AngularTsCompiler.processFilesForTarget (packages/angular-typescript-compiler/index.js:251:26)
    at __bottom_mark__ (/tools/utils/parse-stack.js:69:14)
    at /tools/isobuild/compiler-plugin.js:198:27
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Profile.time (/tools/isobuild/compiler-plugin.js:185:22)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:184:15
    at Function._.each._.forEach (/home/docker/.meteor/packages/meteor-tool/.1.8.0_1.1fqze6b.nyph++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:174:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1109:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:841:34)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:835:18)
    at /tools/isobuild/bundler.js:3143:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3294:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3248:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3124:31)
    at files.withCache (/tools/isobuild/bundler.js:3069:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3069:16)
    at buildCommand (/tools/cli/commands.js:1044:30)
    at Profile.run (/tools/cli/commands.js:909:25)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at Promise.asyncApply (/tools/cli/commands.js:907:18)
    at /home/docker/.meteor/packages/meteor-tool/.1.8.0_1.1fqze6b.nyph++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
[client]: TypeScript Files Compilation: 6908.931ms
[client]: Rollup: 4872.241ms
[client]: HTML Files Compilation: 8.656ms
[client]: SCSS Files Compilation: 1.279ms
[client]: Collecting TypeScript source files: 6.586ms
```

Full log: https://api.travis-ci.org/v3/job/461513940/log.txt

Thanks, Georgy

**Comment by bouchepat** [comment]
Same here
