### ISSUE TITLE
can you help integrating with http://www.meteorkitchen.com

### ISSUE THREAD

**Issue by harinanda** [Urigo/angular-meteor#351]
http://www.meteorkitchen.com  is  getting recognized . help enabling angularjs to  meteorkitchen.com

**Comment by MilosStanic** [comment]
wow this is amazing! didn't know about that site.

**Comment by Urigo** [comment]
It is amazing!

@harinanda What should we do to support it?

**Comment by justin-umesh** [comment]
Hi, I have hosted my site on linode but i'm getting this error. Please help.

http://errors.angularjs.org/1.3.14/$injector/unpr?p0=e
    at http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:466
    at http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:18577
    at r (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:17747)
    at Object.i [as invoke] (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:18084)
    at r (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:17135)
    at http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:17259
    at o (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:851)
    at $ (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:17036)
    at zt (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:18726)
    at s (http://139.162.22.162:3000/3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js:49:6544)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=ckAppWeb&p1=Error%…62.22.162%3A3000%2F3a4c1df74f13888708e0a03b4b28762d1e2bd62e.js%3A49%3A6544)

**Comment by Urigo** [comment]
@justin-umesh how is this related to meteorkitchen?
anyway, looks like it might be a minification problem, try to use strict-di in your dev environment to find what's the problem

**Comment by justin-umesh** [comment]
i have resolved this issue. we need to rename the js files which ends with .ng.js

**Comment by Urigo** [comment]
Opened an issue to meteor kitchen here: https://github.com/perak/kitchen-site/issues/93
