### ISSUE TITLE
Send array to MogoDB and use this as '$in' and '$regex'

### ISSUE THREAD

**Issue by michalmw** [Urigo/angular-meteor#456]
Hello,
i send to 'Meteor.publish' array:
````
name = ['one','two','three']
````

I try create select where meteor check this value is in my fields and if yes return.

For example:
My database:
````
{ "_id" : "x82fzpNvfA74QMSXv", "skladniki" : [ "one" ], "owner" : "jRDNn3L2cCDefJdLP" }
{ "_id" : "MePRYSBTBzKS33ktn", "skladniki" : [ "two", "one" ], "owner" : "jRDNn3L2cCDefJdLP" }
{ "_id" : "aJ6Bhhhrfhv3S9Xxp",  "skladniki" : [ "two" ], "owner" : "jRDNn3L2cCDefJdLP" }
````
i send array
name = ['one];
then i want return 1 and 2 record.

if i send: name = ['one','two'] 
then i want return 1,2 and 3 record;

I try do somethink:
````
return Smoothie.find({
		'skladniki' : {'$in' : [{'$regex': nazwa}]}
	}, options);
````
but, this don't working. Someone can help me?

**Comment by MilosStanic** [comment]
try `$in` and `$regex` without the single quotes, like this: 

```
return Smoothie.find({
        'skladniki' : { $in : [{ $regex : nazwa}]}
    }, options);
```

**Comment by michalmw** [comment]
Try and console back:
````
I20150622-06:24:50.144(-4)? nazwa  T
I20150622-06:24:50.150(-4)? Exception from sub smoothie id XaFN9FpxnXdcqyCLr MongoError: exception: cannot nest $ under $in
I20150622-06:24:50.150(-4)?     at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150622-06:24:50.150(-4)?     at [object Object]._.extend.count (packages/mongo/mongo_driver.js:1002:1)
I20150622-06:24:50.150(-4)?     at [object Object].Cursor.(anonymous function) [as count] (packages/mongo/mongo_driver.js:812:1)
I20150622-06:24:50.150(-4)?     at Object.Counts.publish (packages/tmeasday:publish-counts/publish-counts.js:80:1)
I20150622-06:24:50.150(-4)?     at [object Object]._handler (app/server/smoothie.js:6:9)
I20150622-06:24:50.150(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150622-06:24:50.150(-4)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150622-06:24:50.150(-4)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150622-06:24:50.150(-4)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150622-06:24:50.151(-4)?     at packages/ddp/livedata_server.js:546:1
I20150622-06:24:50.151(-4)?     - - - - -
I20150622-06:24:50.151(-4)?     at Object.toError (/root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20150622-06:24:50.151(-4)?     at /root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1194:31
I20150622-06:24:50.151(-4)?     at /root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
I20150622-06:24:50.151(-4)?     at Server.Base._callHandler (/root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
I20150622-06:24:50.151(-4)?     at /root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
I20150622-06:24:50.151(-4)?     at [object Object].MongoReply.parseBody (/root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20150622-06:24:50.151(-4)?     at [object Object].<anonymous> (/root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
I20150622-06:24:50.152(-4)?     at [object Object].emit (events.js:95:17)
I20150622-06:24:50.152(-4)?     at [object Object].<anonymous> (/root/.meteor/packages/mongo/.1.1.0.zb7oxo++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
I20150622-06:24:50.153(-4)?     at [object Object].emit (events.js:98:17)
````

**Comment by MilosStanic** [comment]
There's definitely an error in your MongoDB query syntax. Google for that error, and see what you can dig up. Anyway, this is 100% not an angular-meteor issue.

**Comment by michalmw** [comment]
Hmm, thix for help.

I did this in another way.

I load in mongo all record, and do filter in angular.js ;-) - and this working ;-)
