### ISSUE TITLE
logout route/function crashes server

### ISSUE THREAD

**Issue by MilosStanic** [Urigo/angular-meteor#876]
Hi guys, my app is crashing on `$meteor.logout()`, like in the socially example, here: 
```
.state('logout', {
            url: '/logout',
            resolve: {
                "logout": ['$meteor', '$state', function($meteor, $state) {
                    console.log('logging out');
                    return $meteor.logout().then(function(){
                        console.log('logged out');
                        $state.go('home');
                    }, function(err){
                        console.log('logout error - ', err);
                    });
                }]
            }
        });
```
The server crashes on `return $meteor.logout()...` after the console log message in previous line gets printed, then the server restarts, and then it enters the `.then()` branch, and prints the `logged out` to console, and finishes `$state` change. 

The error I'm getting when the server crashes is: 

```
W20151115-19:16:04.415(1)? (STDERR) 
W20151115-19:16:04.415(1)? (STDERR) /home/milos/devel/chatapp/.meteor/local/build/programs/server/packages/meteor.js:975
W20151115-19:16:04.416(1)? (STDERR)     throw new Error("Meteor code must always run within a Fiber. " +          
W20151115-19:16:04.416(1)? (STDERR)           ^
W20151115-19:16:04.459(1)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20151115-19:16:04.459(1)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20151115-19:16:04.459(1)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
W20151115-19:16:04.459(1)? (STDERR)     at withoutInvocation (packages/meteor/timers.js:4:1)
W20151115-19:16:04.460(1)? (STDERR)     at bindAndCatch (packages/meteor/timers.js:13:1)
W20151115-19:16:04.460(1)? (STDERR)     at Object._.extend.defer (packages/meteor/timers.js:68:1)
W20151115-19:16:04.460(1)? (STDERR)     at TrackerInstance._deferAndTransfer (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:85:1)
W20151115-19:16:04.460(1)? (STDERR)     at TrackerInstance.requireFlush (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:102:1)
W20151115-19:16:04.461(1)? (STDERR)     at Computation.Tracker.Computation.Computation.invalidate (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:365:1)
W20151115-19:16:04.461(1)? (STDERR)     at Dependency.Tracker.Dependency.Dependency.changed (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:520:1)
W20151115-19:16:04.461(1)? (STDERR)     at [object Object].ReactiveVar.set (packages/reactive-var/reactive-var.js:82:1)
=> Exited with code: 8
```
Can anyone replicate this?

Thanks.

**Comment by Urigo** [comment]
@MilosStanic with the new Angular Meteor 1.3 you should use the regular Meteor API for accounts.
Check out the new changes here: http://info.meteor.com/blog/angular-meteor-1.3
Once you will migrate we can more easily check if the problem is in Angular or Meteor

**Comment by MilosStanic** [comment]
Sorry I didn't update this issue, the problem was with an external lib `peerlibrary:server-autorun`, but the author fixed the bug, and now it works okay.
